### ISSUE TITLE
What problems need to be fixed?

### ISSUE THREAD

**Issue by Asap7772** [chriscush765/hellogit#3]
What problems need to be addressed
Thanks,
Anikait

**Comment by cuuush** [comment]
Plugin manager doesn't correctly create the plugin thread and add it to the
user data class. Your challenge is to find a way for mutiple plugins to
process the messages without hanging the main thread. If you have any
questions, please ask!

The first step should be to look at plugin manager, and make
notifyPlugins() work.

**Comment by Asap7772** [comment]
Thanks!
