### ISSUE TITLE
Why is plugin an interface?

### ISSUE THREAD

**Issue by Asap7772** [chriscush765/hellogit#4]
Sorry about the questions
Thanks,
Anikait Singh

**Comment by cuuush** [comment]
Plugin is an interface because I can create an array list of every running
plugin and not worry about class types. i considered making it an abstract
class but I wanted the plugin creators to implement the methods themselves

**Comment by Asap7772** [comment]
Is there Robotics today?

On Saturday, February 27, 2016, chriscush765 notifications@github.com
wrote:

> Plugin is an interface because I can create an array list of every running
> plugin and not worry about class types. i considered making it an abstract
> class but I wanted the plugin creators to implement the methods themselves
> 
> On Sat, Feb 27, 2016, 11:01 PM Asap7772 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Sorry about the questions
> > Thanks,
> > Anikait Singh
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/chriscush765/hellogit/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chriscush765/hellogit/issues/4#issuecomment-189780806
> .

## 

Anikait Singh

**Comment by cuuush** [comment]
I emailed something to you

**Comment by Asap7772** [comment]
Thanks, I'll work on your Project!

On Sun, Feb 28, 2016 at 11:41 AM, chriscush765 notifications@github.com
wrote:

> I emailed something to you
> 
> On Sun, Feb 28, 2016, 11:37 AM Asap7772 notifications@github.com wrote:
> 
> > Is there Robotics today?
> > 
> > On Saturday, February 27, 2016, chriscush765 notifications@github.com
> > wrote:
> > 
> > > Plugin is an interface because I can create an array list of every
> > > running
> > > plugin and not worry about class types. i considered making it an
> > > abstract
> > > class but I wanted the plugin creators to implement the methods
> > > themselves
> > > 
> > > On Sat, Feb 27, 2016, 11:01 PM Asap7772 <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > 
> > > > Sorry about the questions
> > > > Thanks,
> > > > Anikait Singh
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/chriscush765/hellogit/issues/4.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/chriscush765/hellogit/issues/4#issuecomment-189780806
> > > 
> > > .
> > 
> > ## 
> > 
> > Anikait Singh
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/chriscush765/hellogit/issues/4#issuecomment-189899903>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chriscush765/hellogit/issues/4#issuecomment-189900392
> .

## 

Anikait Singh
